import type { CiviGroup, CiviRecipient } from './types'

export const MOCK_CIVI_GROUPS: CiviGroup[] = [
  {
    id: 12,
    name: 'dynamisch_Alter_9_14_12',
    title: 'dynamisch: Alter 9 - 15 (Smartgruppe)',
    description: 'Automatische Zielgruppe aller Jungen im Alter von 9 bis 15 Jahren.',
    isSmart: true,
    contactCount: 6,
  },
  {
    id: 18,
    name: 'AcWe_Teilnehmer_18',
    title: 'AcWe Teilnehmer',
    description: 'Teilnehmer vergangener Actionwochenenden und Zeltlager (9 - 15 Jahre).',
    isSmart: false,
    contactCount: 5,
  },
  {
    id: 3,
    name: 'Eltern_3',
    title: 'Eltern',
    description: 'Erziehungsberechtigte und Familienkontakte.',
    isSmart: false,
    contactCount: 6,
  },
  {
    id: 4,
    name: 'Werbeverteiler_4',
    title: 'Werbeverteiler',
    description: 'Kontakte, die Flyer und Plakate zum Aushängen und Verteilen erhalten.',
    isSmart: false,
    contactCount: 4,
  },
  {
    id: 11,
    name: 'Newsletter_11',
    title: 'Newsletter',
    description: 'Mailingliste für generelle Info- und Werbemails.',
    isSmart: false,
    contactCount: 6,
  },
]

export const DEFAULT_MOCK_CHILDREN: CiviRecipient[] = [
    {
      id: 201,
      firstName: 'Jonas',
      lastName: 'Müller',
      displayName: 'Jonas Müller',
      salutation: 'Lieber Jonas',
      formalSalutation: 'Liebe Familie Müller',
      age: 11,
      birthDate: '2015-04-12',
      address: {
        street: 'Lindenallee 14',
        postalCode: '37308',
        city: 'Heilbad Heiligenstadt',
      },
      email: 'familie.mueller@beispiel-mail.de',
      phone: '03606 554433',
      mobile: '+49 171 1234567',
      hasValidAddress: true,
      hasValidEmail: true,
      hasValidPhone: true,
    },
    {
      id: 202,
      firstName: 'Lukas',
      lastName: 'Schmidt',
      displayName: 'Lukas Schmidt',
      salutation: 'Lieber Lukas',
      formalSalutation: 'Liebe Familie Schmidt',
      age: 12,
      birthDate: '2014-08-25',
      address: {
        street: 'Bergstraße 7',
        postalCode: '37351',
        city: 'Dingelstädt',
      },
      email: 'schmidt-eichsfeld@web-test.de',
      mobile: '+49 172 9876543',
      hasValidAddress: true,
      hasValidEmail: true,
      hasValidPhone: true,
    },
    {
      id: 203,
      firstName: 'Felix',
      lastName: 'Weber',
      displayName: 'Felix Weber',
      salutation: 'Lieber Felix',
      formalSalutation: 'Liebe Familie Weber',
      age: 10,
      birthDate: '2016-01-19',
      address: {
        street: 'Waldweg 3b',
        postalCode: '37327',
        city: 'Leinefelde-Worbis',
      },
      email: 'weber.felix.eltern@gmx-test.de',
      phone: '03605 601234',
      hasValidAddress: true,
      hasValidEmail: true,
      hasValidPhone: true,
    },
    {
      id: 204,
      firstName: 'Maximilian',
      lastName: 'Becker',
      displayName: 'Maximilian Becker',
      salutation: 'Lieber Max',
      formalSalutation: 'Liebe Familie Becker',
      age: 13,
      birthDate: '2013-11-04',
      address: {
        street: 'Kastanienweg 22',
        postalCode: '37318',
        city: 'Uder',
      },
      email: 'becker-uder@posteo-test.de',
      mobile: '+49 175 4433221',
      hasValidAddress: true,
      hasValidEmail: true,
      hasValidPhone: true,
    },
    {
      id: 205,
      firstName: 'Noah',
      lastName: 'Hoffmann',
      displayName: 'Noah Hoffmann',
      salutation: 'Lieber Noah',
      formalSalutation: 'Liebe Familie Hoffmann',
      age: 9,
      birthDate: '2017-06-30',
      address: {
        street: 'Kirchgasse 5',
        postalCode: '37308',
        city: 'Geisleden',
      },
      email: 'eltern-hoffmann@online.de',
      hasValidAddress: true,
      hasValidEmail: true,
      hasValidPhone: false,
    },
    {
      id: 206,
      firstName: 'Elias',
      lastName: 'Koch',
      displayName: 'Elias Koch',
      salutation: 'Lieber Elias',
      formalSalutation: 'Liebe Familie Koch',
      age: 14,
      birthDate: '2012-03-15',
      address: {
        street: 'Am Sportplatz 9',
        postalCode: '37339',
        city: 'Gernrode',
      },
      mobile: '+49 151 8877665',
      hasValidAddress: true,
      hasValidEmail: false,
      hasValidPhone: true,
    },
  ]

export const MOCK_CIVI_RECIPIENTS: Record<number, CiviRecipient[]> = {
  12: DEFAULT_MOCK_CHILDREN,
  18: DEFAULT_MOCK_CHILDREN.slice(0, 5),
  3: DEFAULT_MOCK_CHILDREN.map((r) => ({
    ...r,
    displayName: `Eltern von ${r.firstName} ${r.lastName}`,
    salutation: r.formalSalutation,
  })),
  4: DEFAULT_MOCK_CHILDREN.slice(0, 4),
  11: DEFAULT_MOCK_CHILDREN,
}
