import type { Event, EventProvider } from './types'

export const mockEvents: Event[] = [
  // 2026 Events
  {
    id: '3aou5v62ip2mlsb79havsrakur@google.com',
    title: 'Zeltlager 2026 – Wegweiser des Schattens',
    slug: 'zeltlager-2026',
    start: new Date('2026-07-08T14:00:00'),
    end: new Date('2026-07-18T13:00:00'),
    location: 'Zeltplatz Wiesental, Thalwenden',
    address: 'Birkenfelder Str., 37318 Uder-Thalwenden',
    ageMin: 9,
    ageMax: 14,
    teaser: '10 Tage Zeltdorf, Sandsteinfelsen, Nachtwache & packende Geländespiele: Das Hauptevent des Jahres im Wiesental!',
    description:
      'Zehn Tage draußen im Wiesental bei Thalwenden. Zehn Tage Zeltstadt, Nachtüberfälle, Felsenklettern, Fahnenklau, Kochen über offenem Feuer und das große Lagermotto: Wegweiser des Schattens. Unser absolutes Jahreshighlight für alle Jungs von 9 bis 14 Jahren!',
    highlights: [
      'Zeltdorf im malerischen Wiesental',
      'Nachtwache, Bundesfeuer & Fackelläufe',
      'Großes Lagerspiel nach Motto-Storyline',
      '100% handyfreie Natur- und Gemeinschaftserfahrung',
    ],
    packingList: [
      'Warmer Schlafsack & dicke Isomatte / Luftbett',
      'Wanderstiefel, feste Schuhe & Gummistiefel',
      'Regenfeste Kleidung, warme Jacke & Badesachen',
      'Essgeschirr, Becher & Besteck im Stoffbeutel',
      'Taschenlampe / Kopflampe mit Ersatzbatterien',
      'Krankenkassenkarte & Impfausweis',
    ],
    image: '/placeholders/camp-hero.svg',
    registrationUrl: 'https://smj-wegweiser.de/civicrm/event/register/?reset=1&id=55',
    category: 'camp',
    contact: {
      name: 'Vinzenz Hupe & Kilian Schlosser',
      role: 'Lagerleitung',
      email: 'vinzenz.hupe@smj-wegweiser.de',
    },
  },
  {
    id: '245fiaddbntagqf2d5n4a0c6na@google.com',
    title: 'Sterntreffen',
    slug: 'sterntreffen-2026',
    start: new Date('2026-08-28T15:00:00'),
    end: new Date('2026-08-30T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '30 € (inkl. Verpflegung, Unterkunft und Betreuung)',
    teaser: 'Das offizielle Zeltlager-Nachtreffen: Drei Tage voller Mutproben, Kameradschaft und wilder Lagergeschichten in der Klause 2.0.',
    description:
      'Hast du den Mut, die Glut des Zeltlagers noch einmal zu entfachen? Dann schnür deine Stiefel und folge uns in die Klause 2.0!\n\nBeim Sterntreffen erwarten dich drei Tage voller Mutproben, Kameradschaft und wilder Geschichten. Das große Wiedersehen für alle Jungs, die im Zeltlager dabei waren. Zusammen schauen wir die Zeltlagerfotos an, kochen gemeinsam und erleben neue Abenteuer rund um die Klause 2.0.',
    highlights: [
      'Großes Wiedersehen der Zeltgemeinschaft',
      'Lager-Rückblick, Fotos & wilde Geschichten',
      'Geländespiele & Mutproben rund um die Klause 2.0',
      '100% handyfreie Zeit – echte Gemeinschaft',
    ],
    packingList: [
      'Persönliche Sachen, Hausschuhe & Kulturbeutel',
      'Krankenkassenkarte & Impfausweis',
      'Kleidung für Abenteuer & feste Schuhe (für draußen)',
      'Schlafsack oder Bettbezug und Bettlaken (Leihgebühr: 5 €)',
      'Taschenlampe oder Kopflampe',
    ],
    image: '/placeholders/story.svg',
    registrationUrl: 'https://smj-wegweiser.de/civicrm/event/register/?reset=1&id=59',
    category: 'weekend',
    contact: {
      name: 'Jonathan Hunold',
      role: 'Zeltlagerleitung',
      email: 'zeltlager@smj-wegweiser.de',
      phone: '0179 6353443',
    },
  },
  {
    id: '5kciib7rruqmg4f6ps8up44ier@google.com',
    title: 'Actionwochenende 1',
    slug: 'actionwochenende-1-2026',
    start: new Date('2026-01-30T16:00:00'),
    end: new Date('2026-02-01T15:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 € (inkl. Vollverpflegung, Übernachtung & Material)',
    teaser: 'Raus aus dem Alltag, rein ins Erlebnis: Ein winterliches Wochenende voller Action, Spaß und echter Gemeinschaft.',
    description:
      'Wenn die Feiertage vorbei sind und der Winter richtig angekommen ist, wird es Zeit für etwas, worauf man sich freuen kann: ein Wochenende voller Action, Spaß und echter Gemeinschaft in der Klause 2.0 in Heiligenstadt!\n\nZusammen erleben wir spannende Aktionen, lustige Spiele, gemeinsames Kochen, gemütliche Abende und jede Menge Abenteuer. Raus aus dem Alltag, rein ins Erlebnis – genau der richtige Neustart ins neue Jahr.\n\nP.S.: Bring gern einen Freund mit – gemeinsam macht’s noch mehr Spaß!',
    highlights: [
      'Spannende Aktionen & Geländespiele im Wald',
      'Gemeinsames Kochen & Küchencrew',
      'Gemütliche Abende am Kamin & Lagerfeuer',
      '100% handyfreie Zeit – echte Gemeinschaft',
    ],
    packingList: [
      'Persönliche Sachen, Hausschuhe & Kulturbeutel',
      'Krankenkassenkarte & Impfausweis',
      'Wetterfeste Abenteuerkleidung & feste Schuhe (für draußen)',
      'Schlafsack oder Bettbezug und Bettlaken (Leihgebühr: 5 €)',
      'Taschenlampe oder Kopflampe',
    ],
    image: '/placeholders/story.svg',
    registrationUrl: 'https://smj-wegweiser.de/civicrm/event/register/?reset=1&id=56',
    category: 'weekend',
    contact: {
      name: 'Jonathan & Vinzenz',
      role: 'Diözesanleitung',
      email: 'vinzenz.hupe@smj-wegweiser.de',
    },
  },
  {
    id: '6p0pd8t82f2bqci0sgosjhq84g@google.com',
    title: 'Familientag im Rahmen der BDKJ Sozialaktion',
    slug: 'familientag-2026',
    start: new Date('2026-04-25T09:00:00'),
    end: new Date('2026-04-26T18:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Spiel, Spaß und Spannung für die ganze Familie im Rahmen der Sozialaktion.',
    description:
      'Gemeinsamer Aktionstag für Kinder, Jugendliche und Familien mit bunten Mitmachstationen, Grillen und Begegnung.',
    category: 'general',
    contact: {
      name: 'SMJ Regio Wegweiser',
      role: 'Organisationsteam',
      email: 'kontakt@smj-wegweiser.de',
    },
  },
  {
    id: '3f5en6h897uqgr7g37nma14vpn@google.com',
    title: 'Actionwochenende 2',
    slug: 'actionwochenende-2-2026',
    start: new Date('2026-05-08T16:00:00'),
    end: new Date('2026-05-10T13:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 € (inkl. Vollverpflegung, Übernachtung & Material)',
    teaser: 'Frühling, Natur & Teamgeist: Das zweite große Actionwochenende des Jahres.',
    description:
      'Draußen im Wald die ersten warmen Tage nutzen: Geländespiele, Kochen über offenem Feuer und Vorbereitung auf das große Sommerzeltlager!\n\nP.S.: Bring gern einen Freund mit – gemeinsam macht’s mehr Spaß!',
    highlights: [
      'Geländespiel im Wald & Taktik-Challenges',
      'Kochen & Grillen am offenen Feuer',
      'Gemeinschaft & Kaminabend',
      '100% handyfreie Zeit',
    ],
    packingList: [
      'Persönliche Sachen, Hausschuhe & Kulturbeutel',
      'Krankenkassenkarte & Impfausweis',
      'Wetterfeste Abenteuerkleidung & feste Schuhe',
      'Schlafsack oder Bettbezug und Bettlaken (Leihgebühr: 5 €)',
      'Taschenlampe oder Kopflampe',
    ],
    image: '/placeholders/wide.svg',
    registrationUrl: 'https://smj-wegweiser.de/civicrm/event/register/?id=57&reset=1',
    category: 'weekend',
    contact: {
      name: 'Jonathan & Vinzenz',
      role: 'Diözesanleitung',
      email: 'vinzenz.hupe@smj-wegweiser.de',
    },
  },
  {
    id: '1t4tc4h6ooi3pd75vgb68q8ujd@google.com',
    title: 'Actionwochenende 3',
    slug: 'actionwochenende-3-2026',
    start: new Date('2026-11-20T16:00:00'),
    end: new Date('2026-11-22T15:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 € (inkl. Vollverpflegung, Übernachtung & Material)',
    teaser: 'Der Jahresabschluss: Kaminabende, Nachtgeländespiel und Gemeinschaft in der Klause 2.0.',
    description:
      'Das dritte Actionwochenende schließt das Jahr ab: Ein starkes Wochenende in der Klause 2.0 mit Nachtmissionen im Wald, gemütlichen Abenden am Kamin und tollem Essen.',
    highlights: [
      'Nachtgeländespiel im Wald mit Fackeln',
      'Burger & Kochen am Feuer',
      'Gemütliche Kaminabende',
      '100% analoge Auszeit',
    ],
    packingList: [
      'Persönliche Sachen, Hausschuhe & Kulturbeutel',
      'Krankenkassenkarte & Impfausweis',
      'Warme Winterkleidung & feste Schuhe',
      'Schlafsack oder Bettbezug und Bettlaken (Leihgebühr: 5 €)',
      'Taschenlampe oder Kopflampe',
    ],
    image: '/placeholders/story.svg',
    registrationUrl: 'https://smj-wegweiser.de/civicrm/event/register/?reset=1&id=58',
    category: 'weekend',
    contact: {
      name: 'Jonathan & Vinzenz',
      role: 'Diözesanleitung',
      email: 'vinzenz.hupe@smj-wegweiser.de',
    },
  },

  // 2025 Events from Calendar
  {
    id: '471u1d0aeele4ganhpu6ci68mksq8gi6hpg3o4v3m79v3k71itu0urilco@google.com',
    title: 'Zeltlager 2025',
    slug: 'zeltlager-2025',
    start: new Date('2025-07-03T10:00:00'),
    end: new Date('2025-07-13T14:00:00'),
    location: 'Zeltplatz Wiesental, Thalwenden',
    address: 'Birkenfelder Str., 37318 Uder-Thalwenden',
    ageMin: 9,
    ageMax: 14,
    teaser: '10 Tage Zeltdorf, Sandsteinfelsen & Nachtwache im Wiesental bei Thalwenden.',
    description: 'Das große Sommerzeltlager 2025 der SMJ Regio Wegweiser im Wiesental bei Thalwenden.',
    category: 'camp',
    contact: {
      name: 'Jonathan Hunold',
      role: 'Zeltlagerleitung',
      email: 'zeltlager@smj-wegweiser.de',
    },
  },
  {
    id: 'g9scr8blg95vbornihr55ctii5tqn2i946o0u6521p10010682o9dbuemq@google.com',
    title: 'Actionwochenende',
    slug: 'actionwochenende-2025',
    start: new Date('2025-04-25T16:00:00'),
    end: new Date('2025-04-28T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 €',
    teaser: 'Frühjahrswochenende in der Klause 2.0: Abenteuer, Gemeinschaft und Kochen am Feuer.',
    description: 'Drei Tage Abenteuer und Gemeinschaft in der Klause 2.0 in Heiligenstadt.',
    category: 'weekend',
    contact: {
      name: 'Jonathan & Vinzenz',
      role: 'Diözesanleitung',
      email: 'vinzenz.hupe@smj-wegweiser.de',
    },
  },
  {
    id: '2pm8h0lktjfouv1m2800d71gm2@google.com',
    title: 'Actionwochenende 3',
    slug: 'actionwochenende-3-2025',
    start: new Date('2025-11-28T16:00:00'),
    end: new Date('2025-12-01T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 €',
    teaser: 'Jahresabschlusswochenende mit Kaminabenden und Nachtspiel.',
    description: 'Das dritte Actionwochenende 2025 in der Klause 2.0.',
    category: 'weekend',
    contact: {
      name: 'Jonathan & Vinzenz',
      role: 'Diözesanleitung',
      email: 'vinzenz.hupe@smj-wegweiser.de',
    },
  },

  // 2024 Events from Calendar
  {
    id: '6eam9hg7qikhvkhujlb9s7bbiq@google.com',
    title: 'Actionwochenende I',
    slug: 'actionwochenende-1-2024',
    start: new Date('2024-02-02T16:00:00'),
    end: new Date('2024-02-04T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 €',
    teaser: 'Winter-Actionwochenende in der Klause 2.0.',
    description: 'Gemeinschaft, Geländespiele und Kaminfeuer zum Auftakt des Jahres 2024.',
    category: 'weekend',
  },
  {
    id: '45op3mg64cjldk13aknc2t5nr1@google.com',
    title: 'Actionwochenende II',
    slug: 'actionwochenende-2-2024',
    start: new Date('2024-06-14T15:00:00'),
    end: new Date('2024-06-16T13:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 €',
    teaser: 'Sommer-Vorbereitungswochenende in der Klause 2.0.',
    description: 'Geländespiele im Wald und Lagerfeuer.',
    category: 'weekend',
  },
  {
    id: '1n1jmdpgfimh9m11piimdoni42@google.com',
    title: 'Zeltlager Thalwenden',
    slug: 'zeltlager-2024',
    start: new Date('2024-06-27T10:00:00'),
    end: new Date('2024-07-07T14:00:00'),
    location: 'Zeltplatz Wiesental, Thalwenden',
    address: 'Birkenfelder Str., 37318 Uder-Thalwenden',
    ageMin: 9,
    ageMax: 14,
    teaser: '10 Tage Zeltlagererlebnis im Wiesental.',
    description: 'Das Sommerzeltlager 2024 im Wiesental bei Thalwenden.',
    category: 'camp',
  },
  {
    id: '1tgl95fhhfpcpm2p666tk1k0cb@google.com',
    title: 'Sterntreffen',
    slug: 'sterntreffen-2024',
    start: new Date('2024-08-09T15:00:00'),
    end: new Date('2024-08-11T13:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '30 €',
    teaser: 'Zeltlager-Nachtreffen in der Klause 2.0.',
    description: 'Drei Tage Wiedersehen, Fotoshow und wilde Geschichten.',
    category: 'weekend',
  },
  {
    id: '6hhe12c6gau5h0amfj7gla5mlk@google.com',
    title: 'Nacht des Heiligtums',
    slug: 'nacht-des-heiligtums-2024',
    start: new Date('2024-08-30T14:00:00'),
    end: new Date('2024-09-01T13:00:00'),
    location: 'Urheiligtum Schönstatt, Vallendar',
    address: '56179 Vallendar, Deutschland',
    teaser: 'Bundesweites Jugendfestival der Schönstatt-Jugend.',
    description: 'Gemeinsame Fahrt zur Nacht des Heiligtums nach Vallendar / Schönstatt.',
    category: 'special',
  },
  {
    id: 'dqm0fs2qgt7l79ihips8t994d0pml52rmut80dgp9q0pi55uc4a8m114jq@google.com',
    title: 'Herbstwoche für Ältere',
    slug: 'herbstwoche-fuer-aeltere-2024',
    start: new Date('2024-09-30T10:00:00'),
    end: new Date('2024-10-07T14:00:00'),
    location: 'Region Wegweiser',
    teaser: 'Herbstfahrt & intensive Gemeinschaft für ältere Jugendliche.',
    description: 'Herbstwoche für ältere Teilnehmer der Region Wegweiser.',
    category: 'special',
  },
  {
    id: '78j7i02p8g0uqbf7vvbkr5krfq@google.com',
    title: 'Actionwochenende III',
    slug: 'actionwochenende-3-2024',
    start: new Date('2024-11-08T16:00:00'),
    end: new Date('2024-11-10T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    ageMin: 9,
    ageMax: 15,
    price: '35 €',
    teaser: 'Jahresabschluss in der Klause 2.0.',
    description: 'Das dritte Actionwochenende 2024 in der Klause 2.0.',
    category: 'weekend',
  },
  {
    id: '49pljnic1git7qjkovvofs9m7o@google.com',
    title: '72h Aktion – Kindertag',
    slug: '72h-aktion-kindertag-2024',
    start: new Date('2024-04-20T09:00:00'),
    end: new Date('2024-04-21T18:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: '72h-Aktion: Spiel, Spaß und Spannung für die ganze Familie!',
    description: 'Gemeinsames Kinder- und Familienfest im Rahmen der bundesweiten 72-Stunden-Aktion.',
    category: 'general',
  },

  // 2023 Events from Calendar
  {
    id: 'vrpkdo4caq4b0oa4jpff7fhcllv65ghi9duga9lte8v2fqqcabcbkn1d9f@google.com',
    title: 'Zeltlager Thalwenden',
    slug: 'zeltlager-2023',
    start: new Date('2023-07-20T10:00:00'),
    end: new Date('2023-07-30T14:00:00'),
    location: 'Zeltplatz Wiesental, Thalwenden',
    address: 'Birkenfelder Str., 37318 Uder-Thalwenden',
    ageMin: 10,
    ageMax: 15,
    teaser: 'Zehn Tage Zeltlagererlebnis für Jungs von 10 bis 15 Jahren.',
    description: 'Sommerzeltlager 2023 im Wiesental bei Thalwenden.',
    category: 'camp',
  },
  {
    id: 'd8q66n95i5l8jlsal0111gaea7penaa5lb7tv2ug13piqn3k92gvu6kvi6@google.com',
    title: 'Utopia Island – Eine neue Welt',
    slug: 'utopia-island-2023',
    start: new Date('2023-08-07T10:00:00'),
    end: new Date('2023-08-14T14:00:00'),
    location: 'Kiehnwerder, Brandenburg an der Havel',
    teaser: 'Sommerfreizeit auf der Insel Kiehnwerder.',
    description: 'Zeltabenteuer auf der Havelinsel Kiehnwerder.',
    category: 'special',
  },
  {
    id: '2n7qh5te42git59jeu7ban7lm8@google.com',
    title: 'Sterntreffen (Zeltlagernachtreffen)',
    slug: 'sterntreffen-2023',
    start: new Date('2023-10-13T16:00:00'),
    end: new Date('2023-10-15T12:30:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Das Nachtreffen zum Zeltlager 2023.',
    description: 'Wiedersehen der Zeltlagergemeinschaft in der Klause 2.0.',
    category: 'weekend',
  },
  {
    id: '0n59rb2mpk1erjiuvr2vfmdfbu@google.com',
    title: 'Actionwochenende 3',
    slug: 'actionwochenende-3-2023',
    start: new Date('2023-12-01T17:00:00'),
    end: new Date('2023-12-03T13:30:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Winterwochenende in der Klause 2.0.',
    description: 'Actionwochenende 3 im Dezember 2023.',
    category: 'weekend',
  },

  // 2022 Events from Calendar
  {
    id: 'h4pfpccj618vk6p0bpo99nbomc4pkqctqsjmina3j9u3m34hjs4dr7vu8q@google.com',
    title: 'Actionwochenende',
    slug: 'actionwochenende-juni-2022',
    start: new Date('2022-06-10T16:00:00'),
    end: new Date('2022-06-12T13:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Frühsommer-Actionwochenende in der Klause 2.0.',
    description: 'Action und Geländespiele in der Klause 2.0.',
    category: 'weekend',
  },
  {
    id: 'tq3jp0bn18450ie580913mv6udfs8257r570am17mvv6ub6llfl37sd88r@google.com',
    title: 'Actionwoche in München',
    slug: 'actionwoche-in-muenchen-2022',
    start: new Date('2022-07-19T10:00:00'),
    end: new Date('2022-07-26T14:00:00'),
    location: 'Herzerichstraße 138-140, 81477 München',
    ageMin: 15,
    teaser: 'Actionwoche für Jungs ab 15 Jahre in München.',
    description: 'Gemeinsame Fahrt nach München für Jugendliche ab 15 Jahren.',
    category: 'special',
  },
  {
    id: 'c26i9ols0mkh5th1kj1358lu44vdblu6k094j6nvnniadtbru46kgibfqn@google.com',
    title: 'Western-Zeltlager Thalwenden',
    slug: 'zeltlager-2022',
    start: new Date('2022-08-04T13:00:00'),
    end: new Date('2022-08-13T12:00:00'),
    location: 'Zeltplatz Wiesental, Thalwenden',
    address: 'Birkenfelder Str., 37318 Uder-Thalwenden',
    ageMin: 10,
    ageMax: 14,
    teaser: 'Western-Zeltlager im Wiesental bei Thalwenden.',
    description: 'Zehn Tage Western-Abenteuer, Cowboys, Saloon und Lagerfeuer.',
    category: 'camp',
  },
  {
    id: 'jk5esg80me7npt6rnaj3dmkkt6c7t0e43uiglrgr1thr14jofp6f19pjpq@google.com',
    title: 'Sterntreffen (Zeltlagernachtreffen)',
    slug: 'sterntreffen-2022',
    start: new Date('2022-11-11T17:00:00'),
    end: new Date('2022-11-13T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Nachtreffen zum Western-Zeltlager 2022.',
    description: 'Rückblick und Wiedersehen in der Klause 2.0.',
    category: 'weekend',
  },
  {
    id: '845o4m0qvog8dl8e5pd9qd0oc1gl8m3a00ve54ie3s76cu63d1j96hca1h@google.com',
    title: 'Actionwochenende',
    slug: 'actionwochenende-dezember-2022',
    start: new Date('2022-12-02T17:00:00'),
    end: new Date('2022-12-04T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Winterwochenende in der Klause 2.0.',
    description: 'Jahresabschluss 2022 in der Klause 2.0.',
    category: 'weekend',
  },

  // 2021 Events from Calendar
  {
    id: '41eel8kqgrm8soof5qd0clibsc@google.com',
    title: 'Bistumsjugendtag',
    slug: 'bistumsjugendtag-2021',
    start: new Date('2021-07-16T10:00:00'),
    end: new Date('2021-07-19T14:00:00'),
    location: 'Bistum Erfurt',
    teaser: 'Gemeinschaft und Jugendbegegnung beim Bistumsjugendtag.',
    description: 'Teilnahme am Bistumsjugendtag 2021.',
    category: 'general',
  },
  {
    id: '7tds6f5umcslfoqvgpq6jgfppj@google.com',
    title: 'Griechen-Zeltlager – Der Ruf der Götter',
    slug: 'zeltlager-2021',
    start: new Date('2021-07-29T10:00:00'),
    end: new Date('2021-08-08T14:00:00'),
    location: 'Zeltplatz Wiesental, Thalwenden',
    address: 'Birkenfelder Str., 37318 Uder-Thalwenden',
    ageMin: 10,
    ageMax: 14,
    teaser: 'Griechen-Zeltlager im Wiesental bei Thalwenden.',
    description: 'Der Ruf der Götter: Zehn Tage Antike, Orakel und Zeltlagerabenteuer.',
    category: 'camp',
  },
  {
    id: '1tappor8r3dviteta27dmngpnn@google.com',
    title: 'Zeltlagernachtreffen',
    slug: 'sterntreffen-2021',
    start: new Date('2021-10-22T16:00:00'),
    end: new Date('2021-10-25T14:00:00'),
    location: 'Klause 2.0, Heiligenstadt',
    address: 'Pater-Kentenich-Weg 3, 37308 Heilbad Heiligenstadt',
    teaser: 'Nachtreffen zum Griechen-Zeltlager 2021.',
    description: 'Wiedersehen der Zeltgemeinschaft in der Klause 2.0.',
    category: 'weekend',
  },
  {
    id: '0h5mhjn9tlf6rqcc0qmsaorbqi@google.com',
    title: 'Gruppenleiterschulung',
    slug: 'gruppenleiterschulung-2021',
    start: new Date('2021-10-29T10:00:00'),
    end: new Date('2021-11-03T14:00:00'),
    location: 'Jugendzentrum Marienberg, Vallendar',
    address: 'Am Marienberg 4, 56179 Vallendar',
    teaser: 'Ausbildung für Gruppenleiter und angehende Leiter.',
    description: 'Gruppenleiterkurs der SMJ im Jugendzentrum Marienberg.',
    category: 'special',
  },
]

export class MockEventProvider implements EventProvider {
  async getEvents(): Promise<Event[]> {
    return mockEvents
  }

  async getEvent(id: string): Promise<Event | null> {
    return mockEvents.find((event) => event.id === id || event.slug === id) ?? null
  }
}
